extends:
  - plugin:vue/essential
  - google
  - "@vue/typescript"
  - "@vue/prettier"
parserOptions:
  parser: "@typescript-eslint/parser"
rules:
  prettier/prettier:
    - error
    - semi: true
      singleQuote: true
      trailingComma: all
